import type { Metadata } from "next";
import { Geist_Mono, Playfair_Display } from "next/font/google";
import "./globals.css";
import Footer from "@/components/footer";
import Navbar from "@/components/navbar";

export const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const playfair = Playfair_Display({
  variable: "--font-playfair",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "J.S Homepage",
  description: "Generated by BlackSynapse",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistMono.variable} ${playfair.variable} bg-gray-100 antialiased`}
      >
        <Navbar />
        <div className="max-w-5xl mx-auto min-h-screen px-4 py-4 flex flex-col">
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
